version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:3000"
    environment:
      - NODE_ENV=production
      - GOOGLE_CLIENT_EMAIL=${GOOGLE_CLIENT_EMAIL}
      - GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    volumes:
      - mysqldb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: smarttrans
      MYSQL_ROOT_PASSWORD: "MDu2!,$$0~=w"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3308:3306"
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    networks:
      - app-network

volumes:
  mysqldb:
    driver: local

networks:
  app-network:
    driver: bridge 